import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/common/footer";
import Navbar from "@/components/common/navbar";
import { CurvedBorder } from "@/components/curvedBorder";

const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const cinzelDecorative = localFont({
  src: "../../public/fonts/CinzelDecorative-Bold.ttf",
  variable: "--font-cinzel-decorative",
  weight: "700",
});

const centaur = localFont({
  src: "../../public/fonts/centaur-regular.ttf",
  variable: "--font-centaur",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cinzelDecorative.variable} ${centaur.variable} antialiased  bg-[#0B0B0D]`}
      >
        <CurvedBorder className="p-2 m-3" strokeColor="#C9A85E" strokeWidth={2}>
                  <CurvedBorder className="p-1" strokeColor="#C9A85E" strokeWidth={1}><Navbar />
        {children}
        </CurvedBorder></CurvedBorder>
        <Footer />
      </body>
    </html>
  );
}
